spring.application.name=consulta-clinica-service
server.port=8082
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/consulta_clinica_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:solca}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:solca}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret=${JWT_SECRET:solca-repositorio-regional-secret-demo-2026}
