spring.application.name=repositorio-clinico-regional-service
server.port=8085
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/repositorio_clinico_regional_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:solca}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:solca}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

servicios.paciente-url=${PACIENTE_SERVICE_URL:http://localhost:8081}
servicios.consulta-url=${CONSULTA_SERVICE_URL:http://localhost:8082}
servicios.laboratorio-url=${LABORATORIO_SERVICE_URL:http://localhost:8083}
servicios.imagenologia-url=${IMAGENOLOGIA_SERVICE_URL:http://localhost:8084}

security.jwt.secret=${JWT_SECRET:solca-repositorio-regional-secret-demo-2026}
