spring.application.name=paciente-maestro-service
server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/paciente_maestro_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:solca}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:solca}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
