spring.application.name=laboratorio-clinico-service
server.port=8083
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/laboratorio_clinico_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:solca}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:solca}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:solca-repositorio-clinico-regional-jwt-secret-2026}
jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS:28800}
auth.username=${AUTH_USERNAME:admin}
auth.password=${AUTH_PASSWORD:admin123}
